
- name: Make sure expire log file exists
  file: path={{item}} owner=bahmni group=bahmni mode=0755 state=touch
  with_items:
    - "{{expire_log_file}}"

- name: check if all artifacts is defined
  include: expire-artifacts.yml
  when: all_artifacts is defined
