- name: bahmni-base-tests
  hosts: bahmni-emr
  sudo: yes
  roles:
    - bahmni-base

- name: bahmni-emr-tests
  hosts: bahmni-emr
  sudo: yes
  roles:
    - bahmni-emr
    - bahmni-lab-connect

- name: bahmni-erp-tests
  hosts: bahmni-erp
  sudo: yes
  roles:
    - bahmni-erp
    - bahmni-erp-connect

- name: bahmni-lab-tests
  hosts: bahmni-lab
  sudo: yes
  roles:
    - bahmni-lab

- name: mysql-replication-tests
  hosts:
    - bahmni-emr-db-slave
  sudo: yes
  roles:
    - mysql-replication

- name: postgres-replication-tests
  hosts:
    - bahmni-erp-db-slave
    - bahmni-lab-db-slave
  sudo: yes
  roles:
    - postgres-replication