- name: Create {{options}} directory
  file:
    path={{ postgres.path }}/{{ options }}
    state=directory
    mode=777

- name: Get timestamp of file name to be created
  command: date +%Y%m%d-%H%M%S
  register: time

- name: Take {{ options }} DB backup
  shell: pg_dump -Upostgres --create  {{ options }} | gzip > {{postgres.path}}/{{options}}/{{ options }}_dump_{{ time.stdout }}.sql.gz
  sudo: yes

- name: Create {{postgres.path}}/{{options}} directory in local machine
  local_action: file path={{postgres.path}}/pgdbdump-backup state=directory mode=0777
  when: copy_to_local_machine == "yes"

- name: Copy {{options}} backup file to local machine
  fetch: src={{postgres.path}}/{{options}}/{{ options }}_dump_{{time.stdout}}.sql.gz dest={{postgres.path}}/{{options}}/ flat=yes
  when: copy_to_local_machine == "yes"
