- name: Make sure destination directory exists
  file: path={{item.backup_to_path}} owner=bahmni group=bahmni mode=0755 state=directory
  with_items:
    - "{{all_artifacts}}"

- name: Check if {{options}}  exists 
  shell: find {{ item.backup_from_path }} -type f | wc -l
  register: file 
  ignore_errors: true
  when: "options =='all'"
  with_items:
     - "{{all_artifacts}}"

- name: Find artifacts to be backedup 
  set_fact: artifacts_to_backup="{{artifacts_to_backup|default([]) + [item.item.name] }}"
  when: "item.stdout is defined and item.stdout != '0'"
  with_items: "{{ file.results }}"
  ignore_errors: true

- name: copy artifacts from src to dest location
  shell:
         tar  -C $(dirname  {{item.backup_from_path}} ) -czvf {{backup_temp_dest_dir}}/$(date +%Y-%m-%d_%H%M%S)-{{item.name}}.tar.gz $(basename {{item.backup_from_path}}) 2>{{backup_log_file}};
         chown bahmni:bahmni {{backup_temp_dest_dir}}/$(ls -t {{backup_temp_dest_dir}} | grep {{item.name}});
         chmod 0755 {{backup_temp_dest_dir}}/$(ls -t {{backup_temp_dest_dir}} | grep {{item.name}});
         cp -rp  {{backup_temp_dest_dir}}/$(ls -t {{backup_temp_dest_dir}} | grep {{item.name}}) {{item.backup_to_path}} 2>{{backup_log_file}};
  async: "{{artifacts.async_timing}}"
  when: "artifacts_to_backup is defined and item.name in artifacts_to_backup"
  with_items:
      - "{{all_artifacts}}"
  ignore_errors: true

- name: Find artifacts that are not backedup
  fail:
       msg: "{{item.item.name}} directory does not exist or it is empty"
  failed_when: "item.stdout is defined and item.stdout == '0'"
  with_items: "{{ file.results }}"