- name: ensure anonymous users are not in the database
  mysql_user:
      name: ''
      login_user: "{{mysql_root_user}}"
      login_password: "{{ mysql_root_password }}"
      state: absent

- name: Create and grant privileges to db user on localhost
  sudo: yes
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    host: "localhost"
    priv: "{{database}}.*:ALL,GRANT"

- name: Create and grant privileges to db user from app server
  sudo: yes
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    host: "{{ item }}"
    priv: "{{database}}.*:ALL,GRANT"
  with_items: "{{ items }}"

- name: Create and grant privileges to root user from app server
  sudo: yes
  mysql_user:
    name: "root"
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    host: "{{ item }}"
    priv: "*.*:ALL,GRANT"
  with_items: "{{ items }}"
  when: "restrict_app_root is not defined"